name: manta_dart
version: 0.0.2

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  mqtt_client: ^3.3.6
  decimal: ^0.3.2
  uuid: ^1.0.0
  json_annotation: ^0.2.3
  logging: ^0.11.3+2
  pointycastle: ^1.0.0-rc4
  asn1lib: ^0.5.3

dev_dependencies:
  test: ^1.3.4
  build_runner: ^0.9.0
  json_serializable: ^0.5.4
  mockito: ^3.0.0
